import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import avatarPic from '../public/bruce-banner.jpeg'
import { useState } from 'react'

const Edit = 'Edit';
const Save = 'Save';
const states = ['New South Wales', 'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia', 'Australian Capital Territory', 'Northern Territory']

export default function Home() {
  const [buttonText, setButtonText] = useState(Edit);
  const [userDetail, setUserDetail] = useState(
    {
      firstName: 'Bruce',
      lastName: 'Banner',
      email: 'bruce.banner@marvel.com',
      phone: '0200000000',
      postcode: '2000',
      State: '',
      company: 'Marvel',
      abn: '12123123123',
      rate: '379',
      dob: '21-may-1970'
    }
  );

  return (
    <div>
      <Head>
        <title>My Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles['container-header']}>
          <h1>My Account</h1>
          <div>
            <button>Edit</button>
          </div>    
        </div>
      </header>
      <main>
        <div className={styles['container-main']}>
          <div className={styles['user-header']}>
            <div>
              <Image className={styles['user-avatar']} src={avatarPic} alt="user avatar" width={70} height={70} />
            </div>          
            <div className={styles['user-name']}>
              <h2>Bruce Banner</h2>
              <button>View Resume</button>
            </div>
            <div>
              <button>Upload Resume</button>
            </div>
          </div>
          <form className={styles['user-info']}>
            <div className={styles['form-item']}>
              <label>First Name</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Last Name</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Email</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Phone Number</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Postcode</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>State</label>
              <select>
                {states.map(state => (
                  <option key={state} value={state}>{state}</option>
                ))}
              </select>
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Company Name</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>ABN</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Hourly Rate</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
            <div className={styles['form-item']}>
              <label>Date of Birth</label>
              <input type="text" />
              <div className={styles['error-message']}></div>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}
